version: "3"

services:
  php:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    volumes:
      - ../capstone/:/var/www/html
      - ./php/php7.1-fpm.conf:/etc/apache2/conf-available/php7.1-fpm.conf
    ports:
      - "8080:8080"

  nginx:
    image: phpdockerio/nginx:latest
    volumes:
        - ../capstone/:/var/www/html
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"
    links:
     - php
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}